"""
Pydantic request / response schemas for the database module.

Keeps all data-shape definitions in one place so that the router,
repository, and RAG service can share them without circular imports.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Car record — mirrors the `cars` PostgreSQL table
# ---------------------------------------------------------------------------

class CarRecord(BaseModel):
    """A single row from the `cars` table."""

    id: int
    brand: str
    model: str
    year: Optional[int] = None
    country_of_origin: Optional[str] = None
    mileage_km: Optional[int] = None
    price_usd: Optional[Decimal] = None
    status: Optional[str] = None          # Available | Reserved | Sold
    category: Optional[str] = None        # Coupe | Sedan | Convertible | Hatchback
    description: Optional[str] = None
    created_at: Optional[datetime] = None

    class Config:
        from_attributes = True


# ---------------------------------------------------------------------------
# Database setup / seed response
# ---------------------------------------------------------------------------

class DatabaseSetupResponse(BaseModel):
    """Response returned after table creation and optional data seeding."""

    status: str
    message: str
    table_created: bool
    rows_inserted: int
    elapsed_seconds: float


# ---------------------------------------------------------------------------
# Natural-language search response
# ---------------------------------------------------------------------------

class DatabaseSearchResponse(BaseModel):
    """Response from a natural-language SQL search against the `cars` table."""

    query: str
    generated_sql: Optional[str] = Field(
        default=None,
        description="The SQL SELECT statement generated by the LLM. None if skipped.",
    )
    rows_found: int
    results: List[Dict[str, Any]]
    answer: str = Field(
        description="A human-readable summary of the search results.",
    )


# ---------------------------------------------------------------------------
# Generic list response
# ---------------------------------------------------------------------------

class CarListResponse(BaseModel):
    """Response for listing all cars in the database."""

    total_count: int
    cars: List[CarRecord]
